name: sky_port
description: "A serial port debugging assistant."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.6.0
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6
  intl: any
  window_manager: ^0.5.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fastforge: ^0.6.0

flutter:
  uses-material-design: true
  generate: true
